### ISSUE TITLE
Cron task to send emails failed

### ISSUE THREAD

**Issue by chrisroos** [freerange/harmonia-old#2]
I think this has failed for the last three Mondays.  I've just run it manually (by changing to the harmonia user and running the command listed in `crontab -l`).

We need to work out why it's failing and, ideally, add some mechanism to get an alert if it fails again in future.

**Comment by lazyatom** [comment]
I've made some recent commits that _may_ help with this, along with adding logging. The errors were visible in /var/mail/harmonia, and were to do with the bundle command not being found. I suspect this is because the path wasn't set properly, but now it's using the recap env stuff, this should work.

If the emails appear properly on Monday, we should close this.

**Comment by chrisroos** [comment]
The emails appeared on Monday so I'm closing this issue.
